#!/usr/bin/env python
import json
import re
import pypandoc

content = {"a": []}

with open("stash.json", "r") as s:
    content = json.loads(s.read())


def convert(html):
    return pypandoc.convert_text(html, format="html", to="markdown")


def create_content(title, content):
    filename = f"../wiki/_content/{title}.md"
    with open(filename, "w") as target:
        target.write(f"---\ntitle: {title}\n---\n")
        target.write(content)


for a in content["a"]:
    title = a["title"]
    title = re.sub("[ /]", "_", title)
    title = re.sub("'", "", title)
    content = a["content"]
    content = str.join(" ", content.splitlines())
    content = re.sub('href="/(.*?)"', r'href="/wiki/\g<1>"', content)
    content = re.sub(" +", " ", content)
    md = convert(content)
    create_content(title, md)
